export default {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  CHECK_USER: 'CHECK_USER',
  LOGOUT: 'LOGOUT',
  UPDATE_PROFILE_IMG: 'UPDATE_PROFILE_IMG',
  GET_ALL_USER_POSTS: 'GET_ALL_USER_POSTS',
  ADD_POST: 'ADD_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
  CLEAR_REDUCER: 'CLEAR_REDUCER'
}
