export default {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  CHECK_USER: 'CHECK_USER',
  LOGOUT: 'LOGOUT',
  UPDATE_PROFILE_IMG: 'UPDATE_PROFILE_IMG',
  CLEAR_USER_REDUCER: 'CLEAR_USER_REDUCER',
  GET_ALL_USER_POSTS: 'GET_ALL_USER_POSTS',
  GET_CURRENT_POST: 'GET_CURRENT_POST',
  ADD_POST: 'ADD_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
  CLEAR_POST_REDUCER: 'CLEAR_POST_REDUCER',
  CLEAR_EMAIL_REDUCER: 'CLEAR_EMAIL_REDUCER',
  SEND_MSG_TO_USER: 'SEND_MSG_TO_USER',
  NEW_POST_MASS_EMAIL: 'NEW_POST_MASS_EMAIL'
}
