export default {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  CHECK_USER: 'CHECK_USER',
  LOGOUT: 'LOGOUT',
  SEND_WELCOME_EMAIL: 'SEND_WELCOME_EMAIL',
  UPDATE_PROFILE_IMG: 'UPDATE_PROFILE_IMG',
  CLEAR_USER_REDUCER: 'CLEAR_USER_REDUCER',
  GET_ALL_USER_POSTS: 'GET_ALL_USER_POSTS',
  GET_CURRENT_POST: 'GET_CURRENT_POST',
  ADD_POST: 'ADD_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
  CLEAR_POST_REDUCER: 'CLEAR_POST_REDUCER'
}
